### ISSUE TITLE
Client error: `POST https://api.vivapayments.com/nativecheckout/v2/transactions` resulted in a `400 Bad Request` response

### ISSUE THREAD

**Issue by Theo4** [alekseykuleshov/viva-php#3]
Hi there!

Tested a transaction and got a 400 Bad request response 
{"status":400,"message":"Invalid Token 34EDD206B6D14997E6A66AA7BE5584D9330ADAE59799BA39C99E167898548FB8","eventId":"0"}

I'm using the $accessToken previously generated

Am I doing something wrong ?

Thanks!

**Comment by alekseykuleshov** [comment]
@Theo4 You need a `charge token` for making the transaction, not the `access token`. The `charge token` should be obtained at the front-end as described here: https://developer.vivawallet.com/native-checkout-v2/ When you got the `charge token`, you can submit it to the back-end and use it for making a transaction. 

`$accessToken` is required to get this `charge token`, on this step: https://developer.vivawallet.com/native-checkout-v2/#step-3-initialize-native-checkout as well the `$baseUrl` is. 

This lib is back-end PHP code only.

**Comment by Theo4** [comment]
Thank you!

**Comment by alekseykuleshov** [comment]
@Theo4 You are welcome.
